# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-04 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0003_remove_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.FileField(default=1, upload_to=b''),
            preserve_default=False,
        ),
    ]
